### ISSUE TITLE
mapRouter entering the wrong route

### ISSUE THREAD

**Issue by EricChen-01** [JEMS-CSE416/JEMS#117]
![Screenshot 2023-12-03 at 11 09 18 PM](https://github.com/JEMS-CSE416/JEMS/assets/76068901/b00a8793-b724-46dd-bee2-daa648f7d3a2)

if someone is attempting to get a map then it is not going to the /:id but rather the / route.

**Comment by miguelcmaramara** [comment]
change query path to something different

**Comment by EricChen-01** [comment]
Fixed!

**Comment by EricChen-01** [comment]
swapped the ordering of the two routers.
