### ISSUE TITLE
export map modalappears under legend

### ISSUE THREAD

**Issue by miguelcmaramara** [JEMS-CSE416/JEMS#149]

**Comment by sammi-lin1** [comment]
<img width="873" alt="image" src="https://github.com/JEMS-CSE416/JEMS/assets/64671027/032c6a31-b382-42bd-8b14-c6e4452f4686">

**Comment by EricChen-01** [comment]
Fixed in [40ee7c9](https://github.com/JEMS-CSE416/JEMS/commit/40ee7c92f6c5e1ea1bfea82071219c4eafb9f16c). Not yet merged.
